services:
  api:
    build:
      context: .
    ports:
      - ${HOST_PORT}:${HOST_PORT}
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: nodeapi_db
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: