services:
  api:
    image: node_api:v0.0.1
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    container_name: nodeapi_db
    image: postgres:16.1
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_USER=${DBUSER}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: